### PR TITLE
Allocations: Change card style

### PR DESCRIPTION
**Pull request by PeterMPhillips**
This PR updates Allocations with styling from the [Figma](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=964%3A27). It is based off of this PR: #1759 because that had already implemented some of the style changes. After that PR gets merged I can rebase this PR to the `dev` branch.
Screenshot from 2019-12-11 10-06-54

### CODE REVIEW

**Comment by topocount** [comment]
@PeterMPhillips is there a reason this is targetting a merged branch?

**Comment by PeterMPhillips** [comment]
@topocount, Chad merge that branch while I was sleeping! I'll rebase it as soon as I start my day

**Comment by topocount** [comment]
> @topocount, Chad merged that branch while I was sleeping! I'll rebase it as soon as I start my day

My bad. just read the PR description more closely

**Comment by PeterMPhillips** [comment]
> Can we remove the `New Allocation` button from inactive budgets? Otherwise this looks good to me. curious to see what @stellarmagnet thinks though
> image

Good point! I'll change that now

**Pull request merged**
