### PR TITLE
Allocations: fix creating new account/budget

### PR DESCRIPTION
**Pull request by chadoh**
We're in a halfway state right now. We don't have new contracts yet, but we're starting to get new UI.

This keeps the new UI working with the current contracts.

The comparison of a raw JS Number object with `MIN_AMOUNT`, which is a `BigNumber`, was also failing intermittently.

### CODE REVIEW

**Comment by chadoh** [comment]
I can fix the step while here. What’s a good step value, do you think? 0.1?

**Comment by chadoh** [comment]
@ottodevs it looks like the browser still starts with the `min` value, when using the keyboard arrow keys to increment the value, even if a larger `step` is defined. We will either need to set `min="0"` and then enforce the `1e-18` minimum with JS-only, or leave it as-is. We can discuss with design later, but for now I added in a `step={0.1}` only.

**Comment by e18r** [comment]
> @ottodevs it looks like the browser still starts with the `min` value, when using the keyboard arrow keys to increment the value, even if a larger `step` is defined. We will either need to set `min="0"` and then enforce the `1e-18` minimum with JS-only, or leave it as-is. We can discuss with design later, but for now I added in a `step={0.1}` only.

Setting a `step={0.1}` creates a HTML5 validation error whenever users input values that aren't multiples of 0.1. Users are still able to submit the form though.

**Comment by chadoh** [comment]
Oh, I did not test that! Eek. Thanks for the catch, @e18r. Are you fixing that already in a separate PR?

**Comment by e18r** [comment]
yeah, don't worry.

**Pull request merged**
