### PR TITLE
feat(template): implement enhanced OE template

### LINKED ISSUE #1524: Add Agent to the OE template
It would be cool to be able to have the Agent app installed automatically when I create an org using the OE template

### PR DESCRIPTION
**Pull request by ottodevs**
# feat(template): implement enhanced OE template

Implementation of Reputation template, featuring our custom Token
manager with Quasi-transferable token (Whitelisted addresses)

 Includes:

- Build scripts
- Dependencies updates
- Contract updates to allow quasi-transferable tokens
- Improvements to gas consumption and contract size
- Adds optional Agent app to manage the Vault
- Revamps template tests to make deps deployment from test file, solving
issues with StandardBounties
- Basic tests wrote and passing

BREAKING CHANGE: Now the template needs 3 tx to create a new DAO instance, so it is not compatible with previous version, it also adds 3 new potential apps (Whitelist oracle, token manager custom and Agent)

Closes #1524, #1604
Co-authored-by: @PeterMPhillips

### CODE REVIEW

**Comment by stellarmagnet** [comment]
I think #1657 supersedes this. Let's close this?

**Comment by ottodevs** [comment]
image

🏆😁

**Comment by ottodevs** [comment]
Update:
- Rebased latest `dev`
- Hoisted dependencies
- Added Agent app
- Added test cases for Agent app install

image

**Comment by ottodevs** [comment]
> It's appears that this branch isn't yet at a point where the frontend can be built for the token manager app, since I'm getting a dependency error regarding a missing tokenAbi json file in script.js. Once past that, I'm getting an error around missing dependencies when I attempt to publish:
> 
> ```
> kevin@X1:~/Projects/tps/shared/integrations/token-manager-custom$ npm run publish:http
> 
> > @autark/apps-token-manager-custom@0.0.1 publish:http /home/kevin/Projects/tps/shared/integrations/token-manager-custom
> > aragon apm publish major --files app/build/ --prepublish-script apm:prepublish
> 
> internal/modules/cjs/loader.js:584
>     throw err;
>     ^
> 
> Error: Cannot find module 'core-js/modules/es.array.slice'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/home/kevin/Projects/tps/node_modules/@aragon/cli/dist/cli.js:4:1)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> ```
> 
> Finally, none of these commands have been hooked up to lerna yet to work with our existing dev flow.
> @PeterMPhillips I'm curious if you get the same error when trying to publish the token manager to a devchain, since you're also a linux user I think

There is no `publish:http` script for `token-manager-custom` , you may want to do this:
`npm run apm:publish:major -- --environment staging --apm.ipfs.rpc https://ipfs.autark.xyz:5001 --ipfs-check false`

But before, you need to install dependencies with `npm i` that is the error you may be getting @topocount 

We probably may want to move this app and whitelist oracle to separate repos? I don't know, but that definitely falls outside of the scope of this PR, the template just needs the contracts of these apps to work.

**Comment by ottodevs** [comment]
> > It's appears that this branch isn't yet at a point where the frontend can be built for the token manager app, since I'm getting a dependency error regarding a missing tokenAbi json file in script.js. Once past that, I'm getting an error around missing dependencies when I attempt to publish:
> > ```
> > kevin@X1:~/Projects/tps/shared/integrations/token-manager-custom$ npm run publish:http
> > 
> > > @autark/apps-token-manager-custom@0.0.1 publish:http /home/kevin/Projects/tps/shared/integrations/token-manager-custom
> > > aragon apm publish major --files app/build/ --prepublish-script apm:prepublish
> > 
> > internal/modules/cjs/loader.js:584
> >     throw err;
> >     ^
> > 
> > Error: Cannot find module 'core-js/modules/es.array.slice'
> >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
> >     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
> >     at Module.require (internal/modules/cjs/loader.js:637:17)
> >     at require (internal/modules/cjs/helpers.js:22:18)
> >     at Object.<anonymous> (/home/kevin/Projects/tps/node_modules/@aragon/cli/dist/cli.js:4:1)
> >     at Module._compile (internal/modules/cjs/loader.js:701:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> >     at Module.load (internal/modules/cjs/loader.js:600:32)
> >     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> >     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> > ```
> > 
> > 
> > Finally, none of these commands have been hooked up to lerna yet to work with our existing dev flow.
> > @PeterMPhillips I'm curious if you get the same error when trying to publish the token manager to a devchain, since you're also a linux user I think
> 
> There is no `publish:http` script for `token-manager-custom` , you may want to do this:
> `npm run apm:publish:major -- --environment staging --apm.ipfs.rpc https://ipfs.autark.xyz:5001 --ipfs-check false`
> 
> But before, you need to install dependencies with `npm i` that is the error you may be getting @topocount
> 
> We probably may want to move this app and whitelist oracle to separate repos? I don't know, but that definitely falls outside of the scope of this PR, the template just needs the contracts of these apps to work.

Alternatively you can use this repo and branch to publish the `token-manage-oracle` as it is the original place where @Quazia did the implementation: https://github.com/AutarkLabs/aragon-apps/tree/token-manager-oracle the code here is 1:1 copy of that contract, same for the `whitelist-oracle` but on that repo both apps are merged in the same folder, so you will need extra work to publish that code.

**Comment by ottodevs** [comment]
Please @topocount could you review the template related code and follow https://github.com/AutarkLabs/product/issues/20 to handle the token-manager-custom deployment path?

**Comment by stellarmagnet** [comment]
@topocount @PeterMPhillips can you do `npm run test` on this branch in the root directory and share if it passes?

**Comment by Quazia** [comment]
Here's the error I'm getting when running testing locally, @topocount I can attempt the publish too and see if it's working. The tests are passing for CI I'm just confused as to why I'm the only one seeing these tests locally.
https://gist.github.com/Quazia/ed0ae9ef5ed4d86970c1d83e472c5866

**Comment by stellarmagnet** [comment]
> We probably may want to move this app and whitelist oracle to separate repos? I don't know, but that definitely falls outside of the scope of this PR, the template just needs the contracts of these apps to work.

I agree with @ottodevs that we should separate the token manager work from this PR.

**Comment by ottodevs** [comment]
I hope with the recent changes and refactor of the code it makes easier to review this PR.

I separated `token-manager-custom` and `whitelist-oracle` to live in: https://github.com/AutarkLabs/token-manager-custom hopefully soon a new monorepo that contains these 2 aragon apps, and makes it easier to sync code with parent `token-manager` or eventual merge in the `aragon/aragon-apps` repo.

The pending step will be publishing both `token-manager-custom`  and `whitelist-oracle` to `npm` so these template can consume them in the `package.json`

**Comment by topocount** [comment]
2 things:
can we add all uncovered template dependencies to skipfiles an also can we:
- [ ] merge in #1869 ?

**Comment by ottodevs** [comment]
> 2 things:
> 
> * [ ]  can we add all uncovered template dependencies to skipfiles or write more tests for them?
> * [ ]  merge in #1869 into this branch

I will increase coverage today

**Pull request merged**
