### PR TITLE
[WIP] Reputation template

### PR DESCRIPTION
**Pull request by PeterMPhillips**
These changes allow for multiple token options when creating a new DAO

First token options:
- Shareholder
- Membership
- Reputation

Second token option:
- Reputation

Also,
- Can set either the first or second token to be in control of Voting and/or Dot Voting
- The Reputation tokens use WhitelistOracle to control who can transfer tokens

### CODE REVIEW

**Comment by stellarmagnet** [comment]
In the way this is currently written, does it require two tokens, or is two tokens optional?

**Comment by PeterMPhillips** [comment]
@stellarmagnet the second token is optional

**Comment by stellarmagnet** [comment]
@PeterMPhillips okay, so it seems we aren't allowing membership + shareholder? I know that isn't exactly "reputation", but we probably want to make this more flexible so we don't have to deal with any more enhancements in the future. Can we update this to a draft PR as the product requirements get finalized, as it seems we have to probably add the agent as well.

**Comment by PeterMPhillips** [comment]
@stellarmagnet Yes, when I discussed this with @Quazia he said to just make the second token reputation, but I think we could give all the options to the second token as well. However, I know @ottodevs is working on template stuff as well and I believe his plan was to selectively merge work from this branch into the branch he was working on, so I'm hesitant to add any more to this branch. On that point, @ottodevs do you even need this PR to remain open?

**Comment by stellarmagnet** [comment]
@PeterMPhillips I wasn't sure what was going on with the two dev streams on the reputation work. Maybe lets keep both PRs as is for now and circle back once the requirements are more clearly documented. cc @ottodevs FYI

**Comment by ottodevs** [comment]
Rebased base branch and merged this PR just for symbolization, the changes are already integrated into the target and properly attributed co-authoring from @PeterMPhillips

**Pull request merged**
