### PR TITLE
Addressbook design check

### PR DESCRIPTION
**Pull request by e18r**
1. Change list layout so that it corresponds with the design.

Before: 
screenshot_2019-08-28_12-38-03_815348116

After: 
screenshot_2019-09-02_08-43-01_876074080

Mobile version:
screenshot_2019-08-29_13-00-04_780942154

2. Don't show Header if there are no contacts.

Before:
screenshot_2019-08-28_12-35-58_754864643

After:
screenshot_2019-08-29_13-22-46_331035060

See previous conversation [here](https://github.com/AutarkLabs/open-enterprise/pull/1194).

### CODE REVIEW

**Comment by e18r** [comment]
@jayalaves 

> * Text size needs to be 16px, the contact name seems larger on the screenshot
> 

I just changed the contact name from 20 to 16px. Address is 15px, left unchanged. Type badge, 12, unchanged. Menu text, 16, unchanged.

**Comment by e18r** [comment]
@jayalaves 

>     * Address inside the AddressBadge is also off, also increase y-value of the text by 1-2 pixels

That's a component that comes directly from AragonUI. Check it out [here](https://ui.aragon.org/identity-badge/), where you can see it's also off. It doesn't seem to be configurable. Maybe the new AragonUI provides new possibilities? @rkzel might be able to provide some advice on that.

**Comment by jayalaves** [comment]
@e18r When in doubt on some css styling, remember that you can check some of the specifics on Figma by clicking into the layers :)
Screenshot 2019-09-02 at 15 23 58

**Comment by e18r** [comment]
@jayalaves Please see the updated screenshot in the description (second one). Also, please don't hesitate to make any further comments.

**Pull request merged**
